language: go
dist: trusty

go:
  - 1.5.2
  - 1.4.3

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - echo "deb https://cran.cnr.Berkeley.edu/bin/linux/ubuntu trusty/" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://mirrors.us.kernel.org/ubuntu/ trusty-backports main restricted universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y r-base r-base-dev
  - sudo R -e "install.packages('jsonlite', repo='http://cran.cnr.Berkeley.edu/')"
  - sudo R -e "install.packages('RCurl', repo='http://cran.cnr.Berkeley.edu/')"

script:
  - go test ./...

notifications:
  email: false