language: go
dist: trusty

go:
  - tip
  - 1.6.1
  - 1.5.4
  - 1.4.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y r-base r-base-dev
  - sudo R -e "install.packages('jsonlite', repo='http://cran.cnr.Berkeley.edu/')"
  - sudo R -e "install.packages('RCurl', repo='http://cran.cnr.Berkeley.edu/')"
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -race ./...
  - ./updatecov.sh

notifications:
  email: false
